### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by alanmatiasdev** [igordcsouza/naruto-hit#2]
Eu adorava esse jogo! Ficava horas jogando com meus amigos. Obrigado por ter desenvolvido

**Comment by igordcsouza** [comment]
Opa! Na real esse jogo ai eu comprei a muitos anos atras. Com base nele eu criei o CDZ - The Game que era na mesma pegada. Foi assim que comecei na area basicamente. 

Inclusive to pensando em voltar com ele no futuro nao muito distante.
